id: A7BD2C26C
title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the Three
  Deities of Long Life'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:20:58.128137
  last_modified_at: 2022-03-01 06:20:58.128145
